version: "3.4"
services:
  dice_roller:
    build: .
    image: dice-roller-gcc:latest
    command: python app/app.py
    volumes: 
      - ./:/app

  tests:
    build: .
    image: dice-roller-gcc:latest
    command: bash -c "pytest --cov=. --disable-warnings "
    volumes: 
      - ./:/app
