version: "3.2"
services:
  dice_roller:
    build: .
    image: dice-roller-gcc:latest
    command: python bot_example.py

  tests:
    build: .
    image: dice-roller-gcc:latest
    command: bash -c "pytest"
